firstname = input('What is your first name ?')
lastname = input('What is your last name ?')
print('My name is : '+ lastname + '.' + firstname)
print('Length of your name : ')
print(len(lastname + '.' + firstname))